USE NHOM1_QUANLYSIEUTHI

INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Bình dân','0902 246 699',N'Số 9 Cốm Vòng, Dịch Vọng Hậu, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Dương Nội','0912 561 552',N'352 Giải Phóng, Thanh Xuân, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Đa Lộc', '0973 470 475',N'Dương Nội, Hà Đông, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Ngọc Linh','0989355310',N'74 Dương Nội, Hà Đông, HN')
INSERT INTO NHACUNGCAP VALUES(N'Công ty Cổ Phần hàng Việt cao cấp','0906 522 468',N'Tổ dân phố Đoàn Kết,P.  Dương Nội, Q. Hà Đông, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Hóa Mỹ phẩm','0985 474 386',N'Số 14/192 Hạ Đình, Thanh Xuân, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp thực phẩm bánh kẹo Minh Khôi','0974 564 533',N'Số 108 A – D2, Ngõ 215 Tô Hiệu, HN')
INSERT INTO NHACUNGCAP VALUES(N'Cty PP Tiên Tiến - Sữa Enfa','0435501946',N'45/35 Khương Hạ, Phường Khương Đình, HN (trong nhà máy PROSIMEX)  ')
INSERT INTO NHACUNGCAP VALUES(N'CTy Đông Dương - Váng sữa monte, xúc xích','0964 751 198',N'Kiều Mai - Từ Liêm - Hà Nội')
INSERT INTO NHACUNGCAP VALUES(N'Cty TNHH XNK TM Việt Linh - Sữa Fami','0918449386',N'360 Bùi Xương Trạch, Thanh Xuân, Hà Nội')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Minh Duẩn - Sữa tắm','0432484361',N'P101 toà nhà SeaProdex- Số 20 láng hạ')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Hạ Long: Xúc xích đồ hộp, váng sữa','0473021136',N'Phòng 202, Tòa nhà CT36, 326 Lê Trọng Tấn, Q.Thanh Xuân, HN')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Sữa Kun - Ngọc Việt','0984152513',N'Số 56A1, KĐT mới Đại Kim – Hoàng Mai, HN')
INSERT INTO NHACUNGCAP VALUES(N'Sữa TH True Milk','0905 988 668',N'Số 369B Nguyễn Trãi, Thanh Xuân, Hà Nội')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Hà Phương','0437592825',N'24-C5 , KĐT Nam Thăng Long, Phú Thượng, Tây Hồ, Hà Nội.')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Pesico - Chuyên nước khoáng','0432 171 903',N'78 Đại An - Văn Quán - Hà Đông')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Rượu vodka Công ty TNHH Beluga Viet Nam','0918 631 388',N'Số 38 - Phố Thắng Lợi - Phường Quỳnh Lôi - Hai Bà Trưng - Hà Nội')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp Mai Phú Quý - Chuyên các loại giấy','0946 622 796',N'TDP Thắng Lợi - Dương Nội - Hà Đông - Hà Nội.')
INSERT INTO NHACUNGCAP VALUES(N'Nhà phân phối cung cấp nước giải khát Việt Đức','0934579123',N'Số nhà 78 Đại An - P. Văn Quán - Hà Đông')